### ISSUE TITLE
net.fabricmc.loader.ModContainer.getInfo() Method not found

### ISSUE THREAD

**Issue by TobseTest** [TehNut/plugin-loader#1]
When starting MC with the following mods, I get the crash below.

- fabric_0.2.7build.127
- ModMenu-1.5.3-84
- plugin-loader-1.14-1.0.6-8

```
java.lang.NoSuchMethodError: net.fabricmc.loader.ModContainer.getInfo()Lnet/fabricmc/loader/ModInfo;
	at info.tehnut.pluginloader.PluginLoaderBuilder.lambda$new$5(PluginLoaderBuilder.java:44)
	at info.tehnut.pluginloader.PluginLoaderBuilder$$Lambda$1380/768342053.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at info.tehnut.pluginloader.PluginLoaderBuilder.<init>(PluginLoaderBuilder.java:45)
	at info.tehnut.pluginloader.PluginLoader.<clinit>(PluginLoader.java:21)
	at info.tehnut.pluginloader.StateHandler.pluginDiscovery(StateHandler.java:16)
	at net.minecraft.class_310.handler$handlePlugins$zdf000(class_310.java:4970)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at info.tehnut.pluginloader.PluginLoaderBuilder.lambda$new$5(PluginLoaderBuilder.java:44)
	at info.tehnut.pluginloader.PluginLoaderBuilder$$Lambda$1380/768342053.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at info.tehnut.pluginloader.PluginLoaderBuilder.<init>(PluginLoaderBuilder.java:45)
	at info.tehnut.pluginloader.PluginLoader.<clinit>(PluginLoader.java:21)
	at info.tehnut.pluginloader.StateHandler.pluginDiscovery(StateHandler.java:16)
	at net.minecraft.class_310.handler$handlePlugins$zdf000(class_310.java:4970)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

```

**Comment by TehNut** [comment]
This mod is no longer needed nor maintained.
